* One
1. Theoretical technicalities may be of major interest for other journals, while the interest of the robotics community is limited to the *applicability* of the proposed approach. Even though authors mention in the paper that the method can be used in online planning, this is not sustained by any *evidence*. Information on the computational aspects are neither reported nor sustained by diagrams from simulation results. Moreover, no comparison with other well-known online methods has been proposed. 

2. As also mentioned by the reviewers, the authors should make an effort in revising the paper by focusing on the aspects that are of interest for the T-RO journal and the robotics community. In particular, the authors should carefully take care of the concerns on the *position* vs *orientation* error, the *computational costs* and *comparisons* with other online methods. 

3. I fully concur with the assessment of the Associate Editor. If you decide to resubmit, please consult the T-RO website http://www.ieee-ras.org/tro for instructions on electronic resubmission. In addition to the largely revised version of your paper, you should upload also a *single pdf file containing your reply to the reviewers' comments* and the *list of changes* made in the paper.

* Two
1. This article presents a method to interpolate a clothoid (or Cornu spiral), which is a non-analytic curve contained in optimal paths for several mobile robots (car-like vehicles, differential or parallel wheels robots at constant velocity, ...).  Fast and precise approximation of such a curve is thus important in robotics.  However, several presentation and technical choices makes it impossible for me to evaluate correctly this paper's contribution.  Specific contributions (with respect to existing works) yet seems IMHO too small for a regular paper.

2. First of all, the error function considered is the relative curvature error.	This error is taken from several publications [20, 18, 17] from computational and applied mathematics.  I am adamant on the fact that this error function is not relevant in robotics (and quite sure it is also in other applications): what needs to be approximated is the position, not the curvature (which is a quadratic function of the arc length - no approximation needed here, on the contrary of what authors pretend in the introduction).  Of course, a small curvature error will lead to a reasonable error in position, but the exact relationship is complex: curvature is integrated into orientation, whose sinus and cosinus are integrated into position.  What is clear is that a bounded curvature error will leads to an increasing position error, which can surely be bounded, as the arc length is, but with probably a higher bound than the one of the curvature error.  The error in position has thus to be used as it was in [11, 14, 16] (or at least added to the curvature error).

3. This article also forgets to give any information on the computation time of the presented method, which is a critical point (in both robotics and other applications [20]). Even the *number* of basic clothoids, and the number of Bézier pieces for each, needed to obtain the approximation is only given once, in Figure 4.  Moreover, the experimental results presented in the article do not convince me:  why is the presented method only compared to other Bézier-based methods [16, 18, 19, 20], and not to other type of approach (e.g. [11], for which an online code is available, making comparison very easy)? Instead of two comparisons (why those?), I would have preferred a *statistic study*, or even better an *evolution of the error with respect to the clothoid length*.  Considering the given results, it seems strange that G2+ method [20] gives worst results than G3 method [18] (the authors of both publications pretended they were equivalent).

4. At last, the article develops several parts which are IMHO useless: e.g., algorithm 1 & 2 are usual, and could have been only mentioned; part II.C is also mainly based on [20], and contains a huge useless Figure 1 (as there is no scale of colors, it has no meaning); etc Please shorten this article by focusing on the specific contributions of your work.  Please, be careful with the notation you use: a length is usually called l, not u; a curve parameter should not be called t (t is time).  Be also careful to define values and functions: in equation (10), B & G are not defined (please add a reference to appendix A which defines them); in algorithm 1, ksi_u does not seem to be defined.  Appendix A needs references or explanations (any justifications for these definitions).

5. As a conclusion, please add the error in position to the curvature error in your experimental results, as well as other results with non-Bézier-based methods (Matlab implementation of [11] is available online at http://act.rasip.fer.hr/mbrezak/ClothoidComputing.html, cf [28] in [11]).	Please also verify your implementation of [20], and propose a more global view of the quality (a statistic approach instead of only two examples).	At last, focus your article on specific contributions to propose a short article.

* Three
1. In this paper, authors propose a method to approximate general clothoids with G^3 geometric continuity. The method can be seen as a three stage approach. In the first stage, elementary clothoids with constraint on winding angle are approximated by Quintic Bezier curves and optimal shape parameters to minimize the maximum curvature error are obtained. In the second stage, by using this optimization procedure, basic clothoids defined in the first quadrant are obtained off-line and stored in a lookup table. Finally, the third stage consists in combining these basic clothoids thought appropriate geometric transformations in order to obtain a general clothoid with a desired accuracy.

2. The paper is well written and clear in general but needs some improvements in its structure and presentation of the ideas in order to make easier for a reader to follow all the steps of the presented method. Some suggestions to improve the clarity: 
  - A brief description of the overall idea and the steps followed throughout the analysis at the top of each section would be useful to the reader;
  - The paper consists in three consecutive approximations: elementary clothoid approximation, basic clothoid approximation and general clothoid approximation. Please, give in advance a definition of these three type of clothoids with an overview of how elemetary clothoids are used to obtain basic ones and general clothoids from basic ones. 
  - Section II could be split in two sections: the first one contains only the clothoid and the quintic bazier curves, while the second deals with elementary clothoid approximation that in turns can be split in subsections (definition of the optimization problem, numerical optimization procedure and divergence problem). 
  - Some figures are too small and in the printed version is very difficult to distinguish between solid and dashed lines (e.g~Fig. 3 and 4).
  
3. The paper seems mathematically correct and the improvement of the proposed method w.r.t. the existing literature is supported by the comparison (section V) of the proposed methods with the ones provided in [16], [18]-[19], and [20]. In particular, authors show the improvements obtained in terms of curvature error, especially in case of non-unit length clothoid approximation. 
  
4. Even though in robotics there are *few* applications where the clothoid curves appear as an extremal of an optimal control problem (Dubins model with inertial control law) or for path smoothing applications, as also stated by authors at the beginning of the introduction, this reviewer believes that the results of this paper are much more relevant in a different field. This is confirmed also by looking at the bibliography. Only one-thirds of the citation come from a journal/conference in robotics. Moreover, the papers authors use for comparison come from computational and applied mathematics, not from robotics. Only [11] and maybe [7] are in the same vein of this paper and come from a robotics journal/conference. I hence ask to the authors to make an effort (not limited to the first paragraph of the introduction) to argument (also with more citations coming from robotics journal/conference) the relevance of this paper in the robotics field and in particular in practical experiments: why should this paper be more relevant in the robotics field instead of in applied mathematics or graphics?

5. Minor comments:
  - Clothoids are extremal of the Dubins model if the vehicle is controlled by the angular acceleration instead of the angular velocity. Please, specify at the beginning of the introduction. 
  - Last sentence of the first paragraph of the introduction: "cltohoid" -> "clothoid". 
  - Section II.C: "...by applying (12)" maybe is (2)? 
  - The sentence before Section III: "...with the exactly the same" -> "...with exactly the same".
