* [[http://www.economist.com/news/china/21710001-foreign-firms-are-worried-china-adopts-tough-cyber-security-law][China adopts a tough cyber-security law]]

- damning 谴责的

  Those damning words from James Zimmerman, chairman of the American Chamber of Commerce in China.

- sweeping 影响广泛的

  describe his view of a sweeping new cyber-security law adopted on November 7th

- dim 悲观的, 黯淡的
  + businesspeople 商业人士
  
  Many foreign businesspeople agree with his dim assessment.

- ostensibly 表面上
  + malicious 恶意的

  Though ostensibly designed to strengthen local networks against malicious hackers,

- nationalist 民族主义
  + Trojan horse 特洛伊木马

  in fact the bill looks very much like a techno-nationalist Trojan horse.

- ICT 

  The law affects both domestic and foreign firms operating on the Chinese mainland and covers a wide range of activity relating to use of the internet and information and communications technologies (ICT).

- come into force 

  It will not come into force until June next year, so it is not yet clear how the rules will be implemented.

- problematic
